import evento1 from '../../assets/images/evento1.jpeg';
import evento2 from '../../assets/images/evento2.jpeg';

export const datosEventos = [
  {
    id: 1,
    titulo: "Conferencia de Tecnología 2025",
    descripcion: "Un evento para conocer las últimas tendencias en tecnología.",
    organizador_id: 1,
    fechaInicio: "2025-10-01T09:00:00",
    fechaFin: "2025-10-01T17:00:00", // agregado
    duracion: 8,
    lugar: "Centro de Convenciones Buenos Aires",
    max_participantes: 300,
    min_participantes: 20,
    precio: 1500,
    tags: ["Tecnología", "Innovación"],
    estado: "activo",
    categoria: "tech",
    imagen: evento1,
  },
  {
    id: 2,
    titulo: "Feria Gastronómica Primavera",
    descripcion: "Disfruta de los mejores sabores de la estación.",
    organizador_id: 2,
    fechaInicio: "2025-10-10T12:00:00",
    fechaFin: "2025-10-10T18:00:00", // agregado
    duracion: 6,
    lugar: "Parque Central",
    max_participantes: 200,
    min_participantes: 10,
    precio: 800,
    tags: ["Gastronomía", "Feria"],
    estado: "activo",
    categoria: "food",
    imagen: evento2,
  },
  {
    id: 3,
    titulo: "Maratón Solidaria",
    descripcion: "Corre por una causa solidaria y ayuda a quienes más lo necesitan.",
    organizador_id: 3,
    fechaInicio: "2025-11-05T07:00:00",
    fechaFin: "2025-11-05T12:00:00", // agregado
    duracion: 5,
    lugar: "Costanera Norte",
    max_participantes: 500,
    min_participantes: 50,
    precio: 1000,
    tags: ["Deporte", "Solidaridad"],
    estado: "activo",
    categoria: "run",
    imagen: evento1,
  },
  {
    id: 4,
    titulo: "Expo Arte Contemporáneo",
    descripcion: "Exposición de artistas emergentes y consagrados.",
    organizador_id: 4,
    fechaInicio: "2025-09-20T15:00:00",
    fechaFin: "2025-09-20T22:00:00", // agregado
    duracion: 7,
    lugar: "Museo de Arte Moderno",
    max_participantes: 150,
    min_participantes: 5,
    precio: 1200,
    tags: ["Arte", "Exposición"],
    estado: "activo",
    categoria: "art",
    imagen: evento2,
  },
  {
    id: 5,
    titulo: "Torneo de Ajedrez Abierto",
    descripcion: "Participa en el torneo abierto para todas las edades.",
    organizador_id: 5,
    fechaInicio: "2025-12-02T10:00:00",
    fechaFin: "2025-12-02T14:00:00", // agregado
    duracion: 4,
    lugar: "Club Social y Deportivo",
    max_participantes: 100,
    min_participantes: 10,
    precio: 500,
    tags: ["Juegos", "Ajedrez"],
    estado: "activo",
    categoria: "chess",
    imagen: evento1,
  },
  {
    id: 6,
    titulo: "Festival de Música Urbana",
    descripcion: "Bandas y DJs en vivo para disfrutar la mejor música urbana.",
    organizador_id: 6,
    fechaInicio: "2025-12-15T18:00:00",
    fechaFin: "2025-12-16T04:00:00", // agregado
    duracion: 10,
    lugar: "Anfiteatro Municipal",
    max_participantes: 400,
    min_participantes: 30,
    precio: 2000,
    tags: ["Música", "Festival"],
    estado: "activo",
    categoria: "music",
    imagen: evento2,
  },
];
